name: CI/CD to Production

on:
  push:
    branches:
      - PROD

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/python-app:prod-${{ github.sha }} .
        docker push ${{ secrets.DOCKER_USERNAME }}/python-app:prod-${{ github.sha }}

    - name: Update Kubernetes Manifest Repo for Prod
      run: |
        git config --global user.email "nahid.mozahid@gmail.com"
        git config --global user.name "nahidmozahid"
        git clone https://github.com/nahidmozahid/python-app-k8s-manifest.git
        cd python-app-k8s-manifest
        git checkout PROD
        cd PROD
        sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/python-app:prod-${{ github.sha }}|g" deployment.yaml
        git add deployment.yaml
        git commit -m "Update Prod image to prod-${{ github.sha }}"
        git push https://nahidmozahid:${{ secrets.GITHUB_TOKEN }}@github.com/nahidmozahid/python-app-k8s-manifest.git PROD
