name: CI/CD to UAT

on:
  push:
    branches:
      - uat

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/sample-python-app:uat-${{ github.sha }} .
        docker push ${{ secrets.DOCKER_USERNAME }}/sample-python-app:uat-${{ github.sha }}

    - name: Update Kubernetes Manifest Repo for UAT
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "GitHub Actions"
        git clone https://github.com/yourname/sample-python-app-manifests.git
        cd sample-python-app-manifests/uat
        sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/sample-python-app:uat-${{ github.sha }}|g" deployment.yaml
        git add deployment.yaml
        git commit -m "Update UAT image to uat-${{ github.sha }}"
        git push https://yourname:${{ secrets.GITHUB_TOKEN }}@github.com/yourname/sample-python-app-manifests.git uat
