name: CI/CD to UAT

on:
  push:
    branches:
      - UAT

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and Push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/python-app:uat-${{ github.sha }} .
        docker push ${{ secrets.DOCKER_USERNAME }}/python-app:uat-${{ github.sha }}

    - name: Update Kubernetes Manifest Repo for UAT
      run: |
        git config --global user.email "nahid.mozahid@gmail.com"
        git config --global user.name "nahidmozahid"

        # Clone the repo fully (fetch all branches)
        git clone --depth=1 --no-single-branch https://github.com/nahidmozahid/python-app-k8s-manifest.git
        cd python-app-k8s-manifest

        # Fetch all branches explicitly (just to be safe)
        git fetch --all

        # Checkout UAT branch directly
        git checkout UAT

        cd UAT

        # Update manifest file
        sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/python-app:uat-${{ github.sha }}|g" deployment.yaml
        git add deployment.yaml
        git commit -m "Update UAT image to uat-${{ github.sha }}"
        git push https://nahidmozahid:${{ secrets.GH_ACCESS_TOKEN }}@github.com/nahidmozahid/python-app-k8s-manifest.git UAT
